### ISSUE TITLE
@FDA77

### ISSUE THREAD

**Issue by hookdr** [MasterRoCcO/i-matik#2]
hallo zusammen, freetz-ng baut für die Fritzbox 7590AX kein Image (8.0) mehr, nur die Oscam. 7490 und 7560 wird einwandfrei durchgebaut. mfg Hookdr könnt Ihr an dem Fehler was machen ?

/bin/sh: 1: set: Illegal option -o pipefail
make[3]: *** [GNUmakefile:177: modules_install.post] Error 2
make[2]: *** [GNUmakefile:196: modules_install] Error 2
make[1]: *** [make/kernel/kernel.mk:246: source/kernel/ref-grx5-7599_08.00/.modules-grx5] Terminated
make: *** [Makefile:47: envira] Terminated
cp: -r not specified; omitting directory '/home/freetz/i-matik/freetz-ng/mips/images/'

ERROR: File '/home/freetz/i-matik/freetz-ng/mips/images/latest.image' does not exist.
mv: cannot stat '/home/freetz/i-matik/freetz-ng/mips/images/.inmemory': No such file or directory
53873
53922

**Comment by MasterRoCcO** [comment]
Du must dich an den wenden 
https://github.com/Freetz-NG/freetz-ng/discussions
das Problem kommt ja von freetz-ng, das hat nichts mit i-matik zu tun! 

Das betrifft ja alle diese Geräte
```
4040
5530
7510
7520
7520B
7530
7530AX (ist ein separater eigener fall)
7590AX
```

**Comment by MasterRoCcO** [comment]
Wenn du da schreibst, lass i-matik da raus! Da er dir sonst nicht antworten wird. Da er da wieder behauptet, das würde daran liegen. Es liegt zu 100% an fehlerhaften patchen in freetz-ng.

**Comment by hookdr** [comment]
Ok, habs versucht . Erfolglos. Fakt ist Freetz_NG baut das Image

Keine Ahnung wo de Fehler liegt.

**Comment by MasterRoCcO** [comment]
freetz-ng bringt halt fehlerhafte patche mit sich, die das Erstellen verhindern.
